//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Crop_Master = new HashSet<Crop_Master>();
            this.SubCategory = new HashSet<SubCategory>();
            this.UserCategoryMapping = new HashSet<UserCategoryMapping>();
            this.Mandi_ProductMaster = new HashSet<Mandi_ProductMaster>();
        }
    
        public long CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> cat_id { get; set; }
        public string CategoryImage { get; set; }
        public string Te_CategoryName { get; set; }
        public string Mr_CategoryName { get; set; }
        public string Hi_CategoryName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Crop_Master> Crop_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubCategory> SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCategoryMapping> UserCategoryMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mandi_ProductMaster> Mandi_ProductMaster { get; set; }
    }
}
