//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandi_OrderProductDetails
    {
        public int Tr_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public string TotalQuantity { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Tr_Date { get; set; }
        public string SelectedQuantity { get; set; }
        public string SelectedProductPrice { get; set; }
    }
}
