//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandi_UserFeedback
    {
        public int FeedbackId { get; set; }
        public string Usercode { get; set; }
        public string VarietyName { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> Tr_Date { get; set; }
    }
}
