//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandi_UserRoles
    {
        public int SerialNumber { get; set; }
        public string MobileNumber { get; set; }
        public int RoleId { get; set; }
    
        public virtual Mandi_Roles Mandi_Roles { get; set; }
        public virtual Mandi_UserInfo Mandi_UserInfo { get; set; }
    }
}
