//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandi_UserRequirement
    {
        public int Tr_Id { get; set; }
        public string Usercode { get; set; }
        public string Requirement { get; set; }
        public Nullable<System.DateTime> Tr_Date { get; set; }
    }
}
