//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandi_InterestedProductForUser
    {
        public long Id { get; set; }
        public string Fk_MobileNumber { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Mandi_InterestedProductForUser Mandi_InterestedProductForUser1 { get; set; }
        public virtual Mandi_InterestedProductForUser Mandi_InterestedProductForUser2 { get; set; }
        public virtual Mandi_UserInfo Mandi_UserInfo { get; set; }
    }
}
