//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandi__Requirement
    {
        public long Id { get; set; }
        public string MobileNumber { get; set; }
        public string BuyerId { get; set; }
        public string BuyerContact { get; set; }
        public string BuyerAddress { get; set; }
        public string CropName { get; set; }
        public string Variety { get; set; }
        public string Quantity { get; set; }
        public string QualitySpecification { get; set; }
        public string DeliveryLocation { get; set; }
        public string ExpectedPrice { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<bool> IsPriceNegotiable { get; set; }
        public string Remarks { get; set; }
    }
}
