//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandi_OrderDetails
    {
        public int Order_Id { get; set; }
        public string Buyer_Mobile { get; set; }
        public string TotalPrice { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public string TotalAmount { get; set; }
        public string Payment_Mode { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> Shipping_Address_Id { get; set; }
        public string ShippingAddress { get; set; }
        public string Order_Status { get; set; }
        public string rzp_order_id { get; set; }
        public string rzp_payment_Id { get; set; }
        public string rzp_payment_status { get; set; }
        public string rzp_payment_Id { get; set; }
        public string rzp_payment_signature { get; set; }
        public string SelectedTotalQty { get; set; }
        public string Buyer_Name { get; set; }
        public string GeoAddress { get; set; }
        public string TransactionId { get; set; }
        public string ResponseCode { get; set; }
        public string TransactionStatus { get; set; }
    }
}
