//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderErrorLogDetails
    {
        public int Tr_Id { get; set; }
        public string Retailer_Id { get; set; }
        public string Retailer_Mobile { get; set; }
        public string PaymentMode { get; set; }
        public string Total_Price { get; set; }
        public string Qty { get; set; }
        public string Csv_File { get; set; }
        public string Error_Msg { get; set; }
        public Nullable<System.DateTime> Tr_Date { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
