//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProductDetails
    {
        public int tr_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string product_id { get; set; }
        public string qty { get; set; }
        public string price { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public string SAP_order_ID { get; set; }
    
        public virtual OrderDetails OrderDetails { get; set; }
    }
}
