//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Master
    {
        public int SkuId { get; set; }
        public string SkuName { get; set; }
        public string ItemCode { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string CurrentQuantity { get; set; }
        public Nullable<System.DateTime> SkuCreatedDate { get; set; }
        public string GSTPercent { get; set; }
        public string ImageUrl { get; set; }
        public string MinQuantittyToBook { get; set; }
        public string MaxQuantittyToBook { get; set; }
        public string PrdCompanyName { get; set; }
        public Nullable<int> AllowSAPOrder { get; set; }
        public string PrdState { get; set; }
        public string Status { get; set; }
    }
}
