//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.OrderErrorLogDetails = new HashSet<OrderErrorLogDetails>();
            this.UserFeedback = new HashSet<UserFeedback>();
            this.UsersAddress = new HashSet<UsersAddress>();
            this.UserWallet = new HashSet<UserWallet>();
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public string UserCode { get; set; }
        public string UserPassword { get; set; }
        public string RetailerName { get; set; }
        public string Address { get; set; }
        public string GeoAddress { get; set; }
        public string Town { get; set; }
        public string CSTNNumber { get; set; }
        public string VATNumber { get; set; }
        public string PANNumber { get; set; }
        public string LicenseNumber { get; set; }
        public string IMEINumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string Pincode { get; set; }
        public Nullable<System.DateTime> SeedLicenseValidity { get; set; }
        public string GSTNumber { get; set; }
        public string Depo { get; set; }
        public string Flag { get; set; }
        public string SapRetailerIdFcmToken { get; set; }
        public string FcmSubscriptionTopic { get; set; }
        public string BankAccountNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string RetailerLastName { get; set; }
        public string HouseNumber { get; set; }
        public string StreetLine1 { get; set; }
        public string StreetLine2 { get; set; }
        public string UserCompany { get; set; }
        public string Type { get; set; }
        public string MobileNumber { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Taluka { get; set; }
        public string Village { get; set; }
        public string Firm_Name { get; set; }
        public Nullable<bool> IsProfileUpdated { get; set; }
        public string RetailerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderErrorLogDetails> OrderErrorLogDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFeedback> UserFeedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAddress> UsersAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWallet> UserWallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}
