//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAddress
    {
        public int tr_id { get; set; }
        public string retailer_id { get; set; }
        public string MobileNumberForOnline { get; set; }
        public string reciver_name { get; set; }
        public string ship_address { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string ship_mobile { get; set; }
        public string email_id { get; set; }
        public string Pan_number { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public Nullable<bool> IsPermanentAddress { get; set; }
        public Nullable<bool> IsMandiUser { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string MobileNumberForMandi { get; set; }
    
        public virtual Mandi_UserInfo Mandi_UserInfo { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
