//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variety_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variety_Master()
        {
            this.Mandi_ProductMaster = new HashSet<Mandi_ProductMaster>();
        }
    
        public int VarietyId { get; set; }
        public string VarietyName { get; set; }
        public int CropId { get; set; }
        public Nullable<bool> Status { get; set; }
        public string VarietyOrigin { get; set; }
    
        public virtual Crop_Master Crop_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mandi_ProductMaster> Mandi_ProductMaster { get; set; }
    }
}
