//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrowIndigo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Mandi_usermaster
    {
        public int tr_id { get; set; }
        public string user_name { get; set; }
        public string user_mobile { get; set; }
        public string user_state { get; set; }
        public Nullable<int> user_role { get; set; }
        public string user_pwd { get; set; }
        public string user_mail { get; set; }
        public Nullable<int> IsLogin { get; set; }
        public string sessionID { get; set; }
        public Nullable<int> LockOut { get; set; }
        public string LockStatus { get; set; }
        public Nullable<int> change_pass { get; set; }
        public string userStatus { get; set; }
    }
}
